### PR TITLE
Add fixed nonce ctr

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by JonZeolla** [comment]
We should update the `README.md` to indicate how to use this repo as we add in components.  Should we consider having a different folder for each lab to make them self-contained, or just use a file naming standard?  Not sure how many you plan to put together.

**Comment by ghost** [comment]
I think different folders would be a good idea now that I think about it

**Comment by ghost** [comment]
Also I'm probably not specific enough in the instructions... thinking I should mention a Python repl and show what XOR looks like in that context, and do markdown instead of txt.

**Comment by JonZeolla** [comment]
Yeah I was going to suggest md as well but wanted to see how you felt about the directories first.  With separate directories, changing the txt to a readme.md makes sense.
Also, it typically helps to have 3 parts - the original instructions, a hints area (with optional code or pseudocode), and a solution (usually in a different dir as to not unintentionally reveal).

**Comment by ghost** [comment]
Good call, I'll get on that

**Comment by JonZeolla** [comment]
I like it, this is great.  I'll try to do a quick run through to double check things.  Do you have any code or pseudocode handy for the hint and/or solution?

**Comment by ghost** [comment]
(sprucing-up of hints forthcoming)

**Comment by JonZeolla** [comment]
Beautiful.  Once it cleans up, this should be good to merge.

**Comment by JonZeolla** [comment]
I will try to review this today or tomorrow, but it's probably just about good.  If you have other exercises in mind it probably makes sense to start focusing on those.  Awesome work man, big thank you.

**Comment by JonZeolla** [comment]
Okay so I had 30 minutes to poke around at this today.  I wasn't able to get through the whole lab but I did open a PR against your branch to reorganize things and make it easier to run through.  If you agree with the changes, feel free to merge them in, and then I will merge in this PR.

**Pull request closed without merging**
